##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/spitekte/loanapp/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R ./public/* $DEPLOYPATH
    - /bin/cp ./public/js/*.js $DEPLOYPATH
    - /bin/cp ./public/css/*.css $DEPLOYPATH/
